---
image: registry.cloud.fits/fits/buildtools:1

stages:
  - push

push:
  stage: push
  script:
    - docker-make --Lint -w cmd/bmcproxy
    - docker-make --Lint -w cmd/console
  only:
    - master
