---
image: registry.cloud.fits/fits/buildtools:1

stages:
  - push

master:
  stage: push
  script:
    - cp Dockerfile.bmcreverseproxy Dockerfile
    - cp docker-make.bmcreverseproxy.yaml docker-make.yaml
    - docker-make -l -x rule2,rule3 -s
    - cp Dockerfile.bmcproxy Dockerfile
    - cp docker-make.bmcproxy.yaml docker-make.yaml
    - docker-make -l -x rule2,rule3 -s
    - cp Dockerfile.console Dockerfile
    - cp docker-make.console.yaml docker-make.yaml
    - docker-make -l -x rule2,rule3 -s
  only:
    - master

branch:
  stage: push
  script:
    - cp Dockerfile.bmcreverseproxy Dockerfile
    - cp docker-make.bmcreverseproxy.yaml docker-make.yaml
    - docker-make -ln -x rule2,rule3 -s
    - cp Dockerfile.bmcproxy Dockerfile
    - cp docker-make.bmcproxy.yaml docker-make.yaml
    - docker-make -ln -x rule2,rule3 -s
    - cp Dockerfile.console Dockerfile
    - cp docker-make.console.yaml docker-make.yaml
    - docker-make -ln -x rule2,rule3 -s
  except:
    - master
