---
image: registry.cloud.fits/fits/buildtools:1

with-slug:
  script: 
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.bmcproxy -f docker-make.bmcproxy.yaml --summary --build-only bmc-proxy-slug 
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.bmcreverseproxy -f docker-make.bmcreverseproxy.yaml --summary --build-only bmc-reverse-proxy-slug 
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.console -f docker-make.console.yaml --summary --build-only metal-console-slug 
  only:
    - merge_requests
    - tags

master:
  script:
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.bmcproxy -f docker-make.bmcproxy.yaml --summary --build-only bmc-proxy-master
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.bmcreverseproxy -f docker-make.bmcreverseproxy.yaml --summary --build-only bmc-reverse-proxy-master 
    - docker-make -x rule2,rule3 --dockerfile Dockerfile.console -f docker-make.console.yaml --summary --build-only metal-console-master 
  only:
    - master
