---
image: registry.cloud.fits/fits/buildtools:1

stages:
  - push

push:
  stage: push
  script:
    - docker-make -l -x rule2,rule3 -s -w bmc-reverse-proxy
    - docker-make -l -x rule2,rule3 -s -w cmd/bmcproxy
    - docker-make -l -x rule2,rule3 -s -w cmd/console
  only:
    - master
