version: '3.5'

networks:
  metal:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  bmc-proxy:
    build:
      context: cmd/bmcproxy
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/bmc-proxy:latest
    container_name: ${BMC_PROXY_CONTAINER_NAME}
    networks:
      - metal
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - ${HOME}/.ssh/id_rsa:/host-key
    ports:
      - "${BMC_PROXY_PORT_HOST}:${BMC_PROXY_PORT}"
    environment:
      BMC_PROXY_PORT: ${BMC_PROXY_PORT}

  bmc-reverse-proxy:
    build:
      context: bmc-reverse-proxy
    image: registry.fi-ts.io/metal/bmc-reverse-proxy:latest
    container_name: ${BMC_REVERSE_PROXY_CONTAINER_NAME}
    networks:
      - metal
    ports:
      - "${BMC_REVERSE_PROXY_PORT_HOST}:${BMC_REVERSE_PROXY_PORT}"

  metal-console:
    build:
      context: cmd/console
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/metal-console:latest
    container_name: ${METAL_CONSOLE_CONTAINER_NAME}
    tty: true
    networks:
      - metal
    ports:
      - "${METAL_CONSOLE_PORT_HOST}:${METAL_CONSOLE_PORT}"
    volumes:
      - ${HOME}/.ssh/id_rsa:/host-key
      - ${HOME}/.ssh/id_rsa.pub:/host-key.pub
    environment:
      METAL_CONSOLE_PORT: ${METAL_CONSOLE_PORT}
      METAL_CONSOLE_METAL_API_ADDRESS: ${METAL_API_ADDRESS}
      METAL_CONSOLE_BMC_REVERSE_PROXY_ADDRESS: bmc-reverse-proxy:${BMC_REVERSE_PROXY_PORT}
      METAL_CONSOLE_PUBLIC_KEY: /host-key.pub
