FROM metalstack/builder:latest as builder

FROM alpine:3.12

RUN apk add \
        ipmitool \
        libvirt-client

COPY certs/server-key.pem /
COPY --from=builder /work/bin/bmc-proxy /

RUN chmod 0600 /server-key.pem
ENV ZAP_LEVEL=info

CMD ["/bmc-proxy"]
