FROM metalstack/builder:latest as builder

FROM alpine:3.12

RUN apk add \
        ipmitool \
        libvirt-client

COPY host-key /
COPY --from=builder /work/bin/bmc-proxy /

RUN chmod 0600 /host-key

CMD ["/bmc-proxy"]
