FROM metalstack/builder:latest as builder

FROM alpine:3.12

COPY host-key.pem ca.pem certs/client.pem certs/client-key.pem /
COPY --from=builder /work/bin/metal-console /

RUN chmod 0600 /host-key.pem /client-key.pem

CMD ["/metal-console"]
