version: '3.5'

networks:
  metal:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  bmc-proxy:
    build:
      context: cmd/bmcproxy
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/bmc-proxy:latest
    container_name: ${BMC_PROXY_CONTAINER_NAME}
    networks:
      - metal
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    ports:
      - "${BMC_PROXY_PORT_HOST}:${BMC_PROXY_PORT}"
    environment:
      BMC_PROXY_PORT: ${BMC_PROXY_PORT}

  metal-mgmt:
    build:
      context: metal-mgmt
    image: registry.fi-ts.io/metal/metal-mgmt:latest
    container_name: ${METAL_MGMT_CONTAINER_NAME}
    networks:
      - metal
    ports:
      - "${METAL_MGMT_PORT_HOST}:${METAL_MGMT_PORT}"

  metal-console:
    build:
      context: cmd/console
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/metal-console:latest
    container_name: ${METAL_CONSOLE_CONTAINER_NAME}
    tty: true
    networks:
      - metal
    ports:
      - "${METAL_CONSOLE_PORT_HOST}:${METAL_CONSOLE_PORT}"
    volumes:
      - ${HOME}/.ssh/id_rsa.pub:/id_rsa.pub
    environment:
      METAL_CONSOLE_PORT: ${METAL_CONSOLE_PORT}
      METAL_CONSOLE_METAL_API_ADDRESS: metal-api:${METAL_API_PORT}
      METAL_CONSOLE_METAL_MGMT_ADDRESS: metal-mgmt:${METAL_MGMT_PORT}
      METAL_CONSOLE_PUBLIC_KEY: /id_rsa.pub
