name: Build latest image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: -p bugs -p unused

    - name: Docker Image
      run: |
        docker build -f Dockerfile -t ghcr.io/metal-stack/metal-console .
        docker push ghcr.io/metal-stack/metal-console
    
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
