name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/}
    - name: Build and push Docker image
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        # pull request images are prefixed with 'pr' to prevent them from overriding released images
        docker build -f Dockerfile.console -t metalstack/metal-console:pr-${GITHUB_TAG_NAME} .
        docker push metalstack/metal-console:pr-${GITHUB_TAG_NAME}
        docker build -f Dockerfile.bmcproxy -t metalstack/bmc-proxy:pr-${GITHUB_TAG_NAME} .
        docker push metalstack/bmc-proxy:pr-${GITHUB_TAG_NAME}
