name: Build and Test

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build the Docker images
      run: |
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -f Dockerfile.console -t metalstack/metal-console:${GITHUB_TAG_NAME} .
        docker push metalstack/metal-console:${GITHUB_TAG_NAME}
        docker build -f Dockerfile.bmcproxy -t metalstack/bmc-proxy:${GITHUB_TAG_NAME} .
        docker push metalstack/bmc-proxy:${GITHUB_TAG_NAME}
